### PR TITLE
Multiline support + \(\) \[\] support

### LINKED ISSUE #2: [Feature request] Allow tex formatting in multiline code blocks
I can't seem to find out how to use multiline LaTeX code.. any way to fix this?

### LINKED ISSUE #6: Use codeblock instead inline code
Hello i am using the plugin to display discord chat gpt bot answers, but chatgpt bot usually answer with codeblocks(3 backquote) instead inlinecode(1 backquote), i would like to make the plugin work with codeblocks and inlinecode anyway the bot is amazing great job.

### PR DESCRIPTION
**Pull request by YabamenoTate**
Closes #2
Closes #6

This is a correction to the parsing process.
Since the line-format code block（\`\`\`...\`\`\`） is contained within the tag "pre," execute the CLOSEST function to rewrite all of it.
Also, &dollar; ...&dollar;, &dollar;&dollar; ...&dollar;&dollar;, in addition to \\(... \\), \\[... \\] formats supported as well.

### CODE REVIEW

**Comment by BinaryQuantumSoul** [comment]
Hello,
Thank you for your work,
Nice to have a fix for the multiline code blocks.

I wonder if the \(\) and \[\] won't happen outside of latex code and then make formatting when not wanted ?
Also why the `\[E=mc^2\]` name ?

**Comment by YabamenoTate** [comment]
I added this title in the sense that it has a three-letter grave accent and also supports writing styles such as  ``\(E=mc^2\)`` or ``\[E=mc^2\]``, but I am not particular about this and can change it.

In LaTeX formulas, especially in display styles, ``\[E=mc^2\]`` is sometimes preferred over ``$$E=mc^2$$`` in some cases.

**Comment by YabamenoTate** [comment]
I want to write `` ```\[E=mc^2\]``` `` Support but when I try to include three grave accents, the markdown is deformed and messed up.

**Comment by YabamenoTate** [comment]
> I wonder if the () and [] won't happen outside of latex code and then make formatting when not wanted ?

Could you elaborate on what you mean by that?

**Comment by BinaryQuantumSoul** [comment]
Changed the title for something more explicit.
For the alternate end markers, we can keep that alternative. If someone has an issue with them, we will see them here.

**Comment by LilTeo14** [comment]
Thanks for keep improvement it!

**Pull request merged**
